/**
 * AiCover — nano-banana generated article imagery with an honest fallback.
 *
 * Shows the AI-generated cover (prompted from the story's own research) the
 * moment it's ready; until then — and on transports without a key — the
 * designed editorial cover holds the frame, so the layout never flashes or
 * breaks. A quiet italic caption marks generated imagery as generated (no
 * sparkle badges in this app), and a subtle re-spin control (hover,
 * top-right) regenerates a take you don't like — the ONLY path that ever
 * re-bills an existing image.
 *
 * Aspect is explicit: wide panels get true 16:9 generations, thumbs 4:3 —
 * no more square images cropped into letterboxes.
 */
import { RefreshCw } from 'lucide-react';
import { useApiKey } from '@/lib/settings/apiKey';
import { useAiCover, type CoverAspect } from '@/lib/ai/aiCover';
import { EditorialCover } from './EditorialCover';
import { cn } from '@/lib/cn';

export function AiCover({
  cacheKey,
  title,
  context,
  url,
  source,
  compact = false,
  aspect,
  className,
}: {
  cacheKey: string;
  title: string;
  /** Reported detail/summary — the research the prompt is built from. */
  context: string | null;
  url: string;
  source: 'news' | 'x' | 'reddit';
  compact?: boolean;
  /** Generated shape; defaults to the surface's natural shape. */
  aspect?: CoverAspect;
  className?: string;
}) {
  const shape: CoverAspect = aspect ?? (compact ? '4:3' : '16:9');
  const { url: generated, respinning, respin } = useAiCover(cacheKey, title, context, shape);
  const hasKey = useApiKey((s) => s.hasKey);
  if (!generated) {
    return (
      <EditorialCover title={title} url={url} source={source} compact={compact} className={className} />
    );
  }
  return (
    <div className={cn('group/aicover relative h-full w-full overflow-hidden', className)}>
      <img
        src={generated}
        alt=""
        className={cn('h-full w-full object-cover', respinning && 'opacity-60')}
      />
      {/* Re-spin: subtle, hover-revealed, owner-key only. */}
      {hasKey && !compact && (
        <button
          type="button"
          onClick={(e) => {
            e.stopPropagation();
            respin();
          }}
          disabled={respinning}
          className="absolute right-2 top-2 grid h-6 w-6 place-items-center rounded-full bg-black/45 text-white/90 opacity-0 backdrop-blur-sm transition-opacity hover:bg-black/60 group-hover/aicover:opacity-100"
          title="Re-spin this image — generates a fresh take (one image call on your key)"
        >
          <RefreshCw className={cn('h-3 w-3', respinning && 'animate-spin')} />
        </button>
      )}
      {/* Honest label, quiet type — no sparkle badges anywhere in this app. */}
      <span
        aria-hidden
        className="pointer-events-none absolute inset-x-0 bottom-0 h-8 bg-gradient-to-t from-black/45 to-transparent"
      />
      <span
        className={cn(
          'absolute font-display italic tracking-wide text-white/80',
          compact ? 'bottom-0.5 right-1.5 text-[7px]' : 'bottom-1.5 right-2.5 text-[10px]',
        )}
        title="Generated illustration, prompted from this story's research — not a photograph."
      >
        {compact ? 'AI-generated' : 'This image was generated by AI'}
      </span>
    </div>
  );
}
